## Example secrets file, copy this file to .secrets.toml, or add env variables by capitalizing
#  the variable names. I.e. secret_1 -> SECRET_1
[default]

test_secret = "default_secret"

[dev]

test_secret = "dev_secret"

[prod]

test_secret = "prod_secret"

[testing]

test_secret = "testing_secret"
