---
steps:
  test-311:
    image: python:3.11-slim
    commands:
      - python -m pip install --user nox
      - python -m nox -e test
    when:
      event: [pull_request, push]
      branch: [main, dev]

  test-312:
    image: python:3.12-slim
    commands:
      - python -m pip install --user tox
      - python -m nox -e test
    when:
      event: [pull_request, push]
      branch: [main, dev]

depends_on:
  - build
